variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  WP_VERSION: latest
  WP_MULTISITE: "0"
  GIT_SSL_NO_VERIFY: 'true'

services:
- mysql:5.7

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git freetds-bin freetds-dev freetds-common libmcrypt-dev --fix-missing -yqq
- docker-php-ext-install mysqli pdo_mysql mbstring
- docker-php-ext-configure pdo_dblib --with-libdir=lib/x86_64-linux-gnu
- docker-php-ext-install -j$(nproc) pdo_dblib

- docker-php-ext-enable mysqli pdo_mysql mbstring pdo_dblib
# Install composer
- curl -sS https://getcomposer.org/installer | php

stages:
  - build
  - test

build_assets:
  stage: build
  image: php:7.2
  script:
    - php composer.phar install
    - bash tests/bin/install-wp-tests.sh wordpress_test root mysql mysql $WP_VERSION
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
  cache:
      paths:
        - vendor/

# Test PHP 7.2
test:7.2:
  stage: test
  image: php:7.2
  script:
    # Install required packages
    - apt-get install libxml2-dev unzip wget zip unzip mysql-client --fix-missing -yqq
    # Install and run unit tests
    - bash tests/bin/install-wp-tests.sh wordpress_test root mysql mysql $WP_VERSION
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors=never