variables:
  GIT_SSL_NO_VERIFY: 'true'

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git libxml2-dev unzip freetds-bin freetds-dev freetds-common vim wget zip unzip subversion mysql-client libmcrypt-dev libmysqlclient-dev --fix-missing -yqq
- ln -s /usr/lib/x86_64-linux-gnu/libsybdb.a /usr/lib/
- docker-php-ext-install pdo_dblib mysqli pdo_mysql mbstring
- docker-php-ext-enable mysqli pdo_mysql mbstring pdo_dblib
# Install composer
- curl -sS https://getcomposer.org/installer | php
- bash bin/install-wp-tests.sh wordpress_test root mysql mysql $WP_VERSION

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  WP_VERSION: latest
  WP_MULTISITE: "0"

stages:
  - build
  - test

build_assets:
  stage: build
  image: php:7.2
  script:
    - php composer.phar install
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
  cache:
      paths:
        - vendor/

# Test PHP 7.2
test:7.2:
  stage: test
  image: php:7.2
  script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors=never